### ISSUE TITLE
makeDocumentSnapshot: TypeError: firestoreService.snapshot_ is not a function

### ISSUE THREAD

**Issue by tettoffensive** [firebase/firebase-functions-test#87]
I get the following error when trying to use `makeDocumentSnapshot`: `TypeError: firestoreService.snapshot_ is not a function`

It seems that it has to do with the following line:
https://github.com/firebase/firebase-functions-test/blob/2574781e959ab019c3e3823a59c26f9b30d65a6c/src/providers/firestore.ts#L83

My code is as follows:

```ts
import FunctionsTest from 'firebase-functions-test';
import onUserWritten from '../onUserWritten.function';

const test = FunctionsTest();

describe('onUserWritten', () => {
  it('should do stuff', async () => {
    const wrapped = test.wrap(onUserWritten);

    const beforeSnap = test.firestore.makeDocumentSnapshot(
      {
        id: 'testUser',
        email: 'a@gmail.com',
      },
      '/users/testUser',
    );
...
```

**Comment by joehan** [comment]
First of, apologies for the very delayed response to this - this repo was unmaintained for a bit, but we are trying to bring it back to life. It looks like the root cause here is that we rely on snapshot_ https://github.com/googleapis/nodejs-firestore/blob/master/dev/src/index.ts#L825, which is private. I'm going to chat with my team about how we should fix this, and try to rework this to use public methods.

**Comment by jekozyra** [comment]
Any updates on this issue?

**Comment by HugoGresse** [comment]
@joehan any news on this issue? Following the officiel (doc)[https://firebase.google.com/docs/functions/unit-testing#using_custom_data] we need to use the `makeDocumentSnapshot`.

**Comment by HugoGresse** [comment]
Maybe @TheIronDev can help as he is the most recent contributors? 
The issue happens with `"firebase-functions-test": "^2.0.2",`

**Comment by TheIronDev** [comment]
I can certainly take a look.

Giving a heads up, it might be a minute while I sort through previous history.

**Comment by TheIronDev** [comment]
@tettoffensive || @HugoGresse

Do either of you have a repo that can reproduce this? I attempted for a while this morning but was not able to reproduce. Might be due to my node version + installed modules.

**Comment by tettoffensive** [comment]
@TheIronDev I do not. I reported this a couple years ago. But it seems like `snapshot_` is still not an exposed method. So I'm not sure why makeDocumentSnapshot _would_ work for you.

**Comment by HugoGresse** [comment]
I've made a small repro : https://github.com/HugoGresse/84-fb-functions-makesnapshot-repro 
BUT, the issue is caused by my stub for firestore... which is 🤦 only a PEBKAC issue

**Comment by TheIronDev** [comment]
@HugoGresse - It wasn't a PEBKAC issue until recently :)

@tettoffensive -

Digging deeper, it looks like this issue was introduced in https://github.com/googleapis/nodejs-firestore/pull/1570, when a bunch of `@internal` were added.

However,
https://github.com/googleapis/nodejs-firestore/pull/1688 added `@private` annotations to a handful of the `snapshot_` overload signatures. 

I believe this makes *most* of the overloads accessible, with the exception of the first signature that does contain the `@internal` [here](https://github.com/googleapis/nodejs-firestore/blob/main/dev/src/index.ts#L861)

I'll try to open up a cl to change the `@internal` to `@private`, stay tuned!

**Comment by tettoffensive** [comment]
@TheIronDev Good find. I think when I initially reported it I was working with the `firebase-admin` package, which I'm not even sure has `snapshot_`. I'll have to dig since I can't really remember if that's the case or not.

**Comment by TheIronDev** [comment]
https://github.com/googleapis/nodejs-firestore/pull/1728 got merged, which resolves this issue! 🎉

**Comment by myspivey** [comment]
Not totally sure what has happened, but this appears to have come back up. Using the latest of all libraries, seeing this across all tests. Validated that @internal has not been added back https://github.com/googleapis/nodejs-firestore/blob/c6c85b66a25b56bd23c19285302a740b0ca85d25/dev/src/index.ts#L1012. `makeDocumentSnapshot` is throwing `firestoreService.snapshot_ is not a function`. For posterity, firebase-functions-test@3.4.0, firebase-admin@13.1.0, @google-cloud/firestore@7.11.0.
