### PR TITLE
Fix #136

### LINKED ISSUE #136: Compiler error after update to v2.0.0
### Version info

**firebase-functions-test:** 2.0.0

**firebase-functions:** 3.20.1

**firebase-admin:** 10.1.0

### Test case

```ts
import firebaseFunctionTest from "firebase-functions-test";

const projectId = "demo-afc";
const test = firebaseFunctionTest({
  projectId,
  storageBucket: "test",
  databaseURL: "http://localhost:9000/?ns=demo-afc",
});
```

```json
    "test:unit": "mocha -r ts-node/register --timeout 10000 --exit src/**/*.test.ts $npm_config_mocha_opts",
    "test": "tsc && npx firebase -P demo-afc emulators:exec --only firestore,database,auth,storage \"npm run test:unit\"",
```
### Steps to reproduce

Run `npm run test`

### Expected behavior

The program compiles and executes the tests.

### Actual behavior

```
node_modules/firebase-functions-test/lib/main.d.ts:5:138 - error TS2305: Module '"./v1"' has no exported member '_makeResourceName'.

5 export { ContextOptions, EventContextOptions, WrappedFunction, WrappedScheduledFunction, CallableContextOptions, makeChange, mockConfig, _makeResourceName, _extractParams, } from './v1';
                                                                                                                                           ~~~~~~~~~~~~~~~~~

node_modules/firebase-functions-test/lib/main.d.ts:5:157 - error TS2305: Module '"./v1"' has no exported member '_extractParams'.

5 export { ContextOptions, EventContextOptions, WrappedFunction, WrappedScheduledFunction, CallableContextOptions, makeChange, mockConfig, _makeResourceName, _extractParams, } from './v1';
```

The typescript compiler fails due to a type error. I can see that `_extractParams` and `_makeResourceName` are exported in `v1.js`, but are missing from the exports in `v1.d.ts`.

### PR DESCRIPTION
**Pull request by TheIronDev**
This commit fixes a breaking issue with the test sdk.

Exports won't function properly with functions annotated with @internal.

Which, was a little unexpected... but here we are. :)

### CODE REVIEW

**Review by taeold — APPROVED** [review]
Please update PR description!
