### ISSUE TITLE
Module '"firebase-functions"' has no exported member 'crashlytics'

### ISSUE THREAD

**Issue by sceee** [firebase/firebase-functions-test#97]
### Version info

**firebase-functions-test:** v0.2.3

**firebase-functions:** v3.13.2

**firebase-admin:** v9.8.0

### Test case

N/A, it does not seem to be related to any of our user code but only the firebase libraries in relation to each other.

### Steps to reproduce

Execute `tsc` in a project with
* `firebase-functions-test` v0.2.3
* `firebase-functions` v3.13.2
* `firebase-admin` v9.8.0

### Expected behavior

No compilebreak, no conflicting types.

### Actual behavior

The following compilebreak occurs
```
node_modules/firebase-functions-test/lib/providers/crashlytics.d.ts(1,10): error TS2305: Module '"firebase-functions"' has no exported member 'crashlytics'.
```

**Comment by sceee** [comment]
It seems this is caused by https://github.com/firebase/firebase-functions/pull/866

**Comment by beeoohbee** [comment]
This issue causing us issue as well, we cannot upgrade past firebase-functions@3.13.1

**Comment by michaelprichardson** [comment]
Also running into this issue, will the PR be merged and released soon?

**Comment by sceee** [comment]
@Salakar @abeisgoat is there any chance you review my PR for this issue (or forward it to the respective person) and create a release afterwards?

As there have been no PRs merged for a longer time in this repo it seems the open PRs have been overseen.

**Comment by nerami** [comment]
In the meantime, rolling back to `firebase-functions@3.13.2` fixed the issue: https://github.com/firebase/firebase-functions/tree/v3.13.2

**Comment by taeold** [comment]
Hi folks. We cut a new release that should resolve this issue:

https://www.npmjs.com/package/firebase-functions-test/v/0.3.0

Please let us know if you continue to have problems.
